### ISSUE TITLE
Support pasting

### ISSUE THREAD

**Issue by vadimdemedes** [vadimdemedes/ink-text-input#1]
Currently if you paste into an empty field, only the last char is displayed. Here's the log of keypress events and output when pasting "atom":

```
{ sequence: 'a',
  name: 'a',
  ctrl: false,
  meta: false,
  shift: false }
{ sequence: 't',
  name: 't',
  ctrl: false,
  meta: false,
  shift: false }
{ sequence: 'o',
  name: 'o',
  ctrl: false,
  meta: false,
  shift: false }
{ sequence: 'm',
  name: 'm',
  ctrl: false,
  meta: false,
  shift: false }
m
m
m
m
```

Notice that output follows keypress events, so it seems that keypress events arrive all at once for each char before an update to stdout is written.

Currently batching of `setState()` isn't supported in Ink, but I don't think it's related / going to help this. Maybe some queueing of keypress events should be implemented in `<TextInput>`.

**Comment by sekistner** [comment]
See my pull request #5.

**Comment by ivanross** [comment]
With the current version, pasting seems to work. All characters are added to `value`, but the cursor position always moves by 1.

**Comment by vadimdemedes** [comment]
Fixed!
