### ISSUE TITLE
handleSubmit

### ISSUE THREAD

**Issue by entrptaher** [vadimdemedes/ink-text-input#16]
The quickstart on readme.md mentioned `this.handleSubmit = this.handleSubmit.bind(this);`, which is empty and will set off error. 

Moreover, `onChange` is handled properly while `onSubmit` is not.

Maybe we need to handle `ENTER`?

```js
if(s === ENTER && this.props.onSubmit && value !== originalValue){
  return this.props.onSubmit(value);
}
```

**Comment by SimenB** [comment]
I was just about to open an issue for this. Would be awesome! (And I see the deprecated password input component has `onSubmit`)

**Comment by danrspencer** [comment]
3rded - for now I've copied the code into a file locally and added my own `onSubmit` method

**Comment by jcar787** [comment]
4thed - I added my own custom onSubmit too.

**Comment by entrptaher** [comment]
@danrspencer  @jcar787 let's do a pull request, what do you say? :D

**Comment by jcar787** [comment]
@entrptaher I think you should do it since you discovered the issue first and added the gist. 😊
Thanks for the gist though.

**Comment by entrptaher** [comment]
You are right. 
However, I dug deep into it and found I had problem with cursorOffset when I submit using ENTER. 
Then I asked on this issue :D

**Comment by mAAdhaTTah** [comment]
[Hook version](https://jamesdigioia.com/gistpens/useonenter/). You don't get the value from it though.

**Comment by vadimdemedes** [comment]
I guess I accidentally removed it when migrating to Ink 2 or earlier 🤷‍♂️ If anyone's willing to help out with this, would be great! If not, I will take care of it bit later this week.

**Comment by SimenB** [comment]
#19 is merged, this can be closed 🎉

**Comment by entrptaher** [comment]
@SimenB let me test the cursorOffset, I am really curious about it. :D

**Comment by entrptaher** [comment]
This works flawlessly. 
The issue can be closed. 

# Result:
![](https://raw.githubusercontent.com/entrptaher/playground-ink-text-input/master/demo.gif)

[Git repo](https://github.com/entrptaher/playground-ink-text-input)

Many thanks everyone. 
Gonna go find next bug :D
