### ISSUE TITLE
Usage example doesn't work 

### ISSUE THREAD

**Issue by alechp** [vadimdemedes/ink-text-input#25]
## Summary
* Ink works 
* Usage example in ink-text-input does not work
* Error: "stdin.setRawMode is not a function"

### Ink is working as expected 

**input**
![a_code_demo](https://user-images.githubusercontent.com/3058939/54648809-de672f00-4a64-11e9-86dc-537c74418d35.png)

**output**
<img width="948" alt="a_output_demo" src="https://user-images.githubusercontent.com/3058939/54648814-e3c47980-4a64-11e9-8b41-bc4d911fd14b.png">

### `ink-text-input` "Usage" example is not working
> Error: "stdin.setRawMode is not a function"

**input**
![b_code_TextInput](https://user-images.githubusercontent.com/3058939/54648830-f048d200-4a64-11e9-94bf-b782ac777cc2.png)

**output**
<img width="946" alt="b_output_TextInput" src="https://user-images.githubusercontent.com/3058939/54648869-18383580-4a65-11e9-8ce0-a0b5f1245fd5.png">

### `ink-text-input` after implementing componentDidCatch
> Did this to address the error bounds request in previous error message

**input**
![c_code_componentDidCatch](https://user-images.githubusercontent.com/3058939/54648884-25552480-4a65-11e9-9bcc-33aad0b6b4e7.png)

**output**
<img width="946" alt="c_output_componentDidCatch1" src="https://user-images.githubusercontent.com/3058939/54648898-30a85000-4a65-11e9-9f32-14f4e86c6a5d.png">

<img width="946" alt="c_output_componentDidCatch2" src="https://user-images.githubusercontent.com/3058939/54648910-3d2ca880-4a65-11e9-9b6e-f04d8a949be6.png">

---

Possibly related to https://github.com/vadimdemedes/ink/issues/166

**Comment by mAAdhaTTah** [comment]
Does the usage example work when running with `node` directly? Probably related to the issue you cited, specifically due to usage of `nodemon`.

**Comment by alechp** [comment]
Yes, running with `node` directly works. 

<img width="950" alt="Screen Shot 2019-03-26 at 10 25 39 AM" src="https://user-images.githubusercontent.com/3058939/55019126-84f58780-4fb1-11e9-8a3b-31be085122bd.png">

**Comment by vadimdemedes** [comment]
@mAAdhaTTah is right, any component that expects to read from stdin won't work if you're not executing it directly.

**Comment by alechp** [comment]
@vadimdemedes Roger. 

For anyone else running into the same issue with nodemon specifically, add the `--no-stdin` flag.

Reference: https://github.com/remy/nodemon/issues/1367

Example:
```
"dev:liveReloadedModule": "nodemon --no-stdin --watch src/index.js --exec 'babel-node src/index.js'",
```

**Comment by vadimdemedes** [comment]
Thanks for getting back about this issue with your solution, @alechp!
