### ISSUE TITLE
handleInput still receiving data after the component is unmounted

### ISSUE THREAD

**Issue by danikaze** [vadimdemedes/ink-text-input#27]
This happens in a corner case when the component is unmounted due to a key input (which makes the component doesn't render anymore) but the event emitter is already iterating the listeners.

The reason this happens is, because the events emitter create a copy of the listeners to iterate them, and the `stdin.removeListener` call happens after the copy is done, therefore the `handleInput` listener receives the event and tries to update the state in a unmounted component, triggering a warning/error

**Comment by gersomvg** [comment]
@vadimdemedes Could this be a regression in 4.0.1?
