### ISSUE TITLE
Hope UncontrolledTextInput can clears input after submission

### ISSUE THREAD

**Issue by bakabird** [vadimdemedes/ink-text-input#35]
I found UncontrolledTextInput very useful. However, there is an inconvenient place that after UncontrolledTextInput submits the input, the value will stay in the input. This is inconvenient to use, as input in the CLI is usually cleared after submission. I made the following simple adjustments based on your program. Hopefully, you have a comfortable way to add props to the application to control whether it clears its input after submission.

```js
export class UncontrolledTextInput extends PureComponent {
	state = {
		value: ''
	}

	setValue(value) {
		this.setState({value});
	}
	clearValue(value){
		this.props.whenSubmit && this.props.whenSubmit(value)
		this.setState({
			value: ''
		})
	}

	setValue = this.setValue.bind(this);

	render() {
		return <TextInputWithStdin {...this.props} onSubmit={this.clearValue} value={this.state.value} onChange={this.setValue}/>;
	}
}
```

Thank you for your work！

**Comment by vadimdemedes** [comment]
> This is inconvenient to use, as input in the CLI is usually cleared after submission
Hm, I don't think I agree with that, most CLI tools I've used preserve everything that was displayed before and just add new inputs as needed. See https://github.com/SBoudrias/Inquirer.js as an example.
