### ISSUE TITLE
package requires 'ink' without declaring it as a dependency

### ISSUE THREAD

**Issue by mprast** [vadimdemedes/ink-text-input#48]
https://github.com/vadimdemedes/ink-text-input/blob/master/src/index.js#L3
https://github.com/vadimdemedes/ink-text-input/blob/master/package.json#L40

Notably, this breaks installation under [yarn v2](https://next.yarnpkg.com/). Might make sense to add ink as a peer dependency?

**Comment by mprast** [comment]
same goes for chalk, react

**Comment by mprast** [comment]
https://github.com/vadimdemedes/ink-text-input/pull/49

**Comment by vadimdemedes** [comment]
Fixed in 3.2.2.
