### ISSUE TITLE
Cursor is hidden in input when placeholder is set

### ISSUE THREAD

**Issue by bence-toth** [vadimdemedes/ink-text-input#52]
If the `placeholder` prop is set, the cursor becomes invisible, even if `showCursor` is set to `true`.

I'm not really sure how I would expect this to be handled, I just noticed that it is slightly confusing, because the app does not look like it is waiting for input.

Is there a particular reason you decided to make it this way? Or am I missing something?

**Comment by charlex** [comment]
I also find this behavior confusing, as I do not know where to find the input.
