### ISSUE TITLE
Allow `value` on `UncontrolledTextInput`

### ISSUE THREAD

**Issue by NSExceptional** [vadimdemedes/ink-text-input#65]
Why does `UncontrolledTextInput` not allow an explicit initial value? For a stateful app, this is painful. I should be able to provide both a placeholder and a value and have it display the placeholder if the value is empty/nullish.

**Comment by vadimdemedes** [comment]
Added `initialValue` prop in [`v4.0.3`](https://github.com/vadimdemedes/ink-text-input/releases/tag/v4.0.3).
